-- Gymmy database setup. Generated by scripts/build-setup-sql.sh from supabase/migrations.
-- Paste the whole file into Supabase → SQL Editor → New query → Run. Safe to re-run.

-- ===== 20260930000000_gyms.sql =====
-- Gymmy: gyms, leaderboards, video entries and reports.
-- Run once in the Supabase SQL Editor (or `supabase db push`). See docs/gyms-spec.md.

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  username text not null unique check (username ~ '^[a-z0-9_.]{3,20}$'),
  companion_id text not null default 'kong' check (char_length(companion_id) <= 20),
  strikes int not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.gyms (
  id uuid primary key default gen_random_uuid(),
  kind text not null check (kind in ('public', 'private')),
  name text not null check (char_length(btrim(name)) between 3 and 40),
  area text check (char_length(area) <= 40),
  invite_code text unique,
  created_by uuid references public.profiles (id) on delete set null default auth.uid(),
  created_at timestamptz not null default now()
);

-- One shared entry per public gym, so "Gold's Downtown" isn't added five times.
create unique index if not exists gyms_public_name_area on public.gyms (lower(btrim(name)), lower(coalesce(btrim(area), '')))
  where kind = 'public';

create table if not exists public.gym_members (
  gym_id uuid not null references public.gyms (id) on delete cascade,
  user_id uuid not null references public.profiles (id) on delete cascade default auth.uid(),
  joined_at timestamptz not null default now(),
  primary key (gym_id, user_id)
);

create index if not exists gym_members_user on public.gym_members (user_id);

create table if not exists public.entries (
  id uuid primary key default gen_random_uuid(),
  gym_id uuid not null references public.gyms (id) on delete cascade,
  challenge_id text not null check (challenge_id in (
    'bench_1rm', 'squat_1rm', 'deadlift_1rm', 'ohp_1rm',
    'pullups_max', 'pushups_1min', 'plank_hold', 'row_500m')),
  user_id uuid not null references public.profiles (id) on delete cascade default auth.uid(),
  value numeric not null check (value > 0 and value < 100000),
  bodyweight_kg numeric check (bodyweight_kg between 20 and 400),
  video_path text not null,
  status text not null default 'live' check (status in ('processing', 'live', 'hidden', 'removed')),
  created_at timestamptz not null default now()
);

create index if not exists entries_board on public.entries (gym_id, challenge_id) where status = 'live';
create index if not exists entries_global on public.entries (challenge_id) where status = 'live';
create index if not exists entries_user on public.entries (user_id);

create table if not exists public.reports (
  entry_id uuid not null references public.entries (id) on delete cascade,
  reporter_id uuid not null references public.profiles (id) on delete cascade default auth.uid(),
  kind text not null check (kind in ('invalid', 'inappropriate')),
  reason text not null check (char_length(reason) <= 200),
  -- Set by trigger: only established, trusted accounts move the needle.
  counted boolean not null default false,
  resolved boolean not null default false,
  created_at timestamptz not null default now(),
  primary key (entry_id, reporter_id)
);

create table if not exists public.blocks (
  user_id uuid not null references public.profiles (id) on delete cascade default auth.uid(),
  blocked_id uuid not null references public.profiles (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, blocked_id),
  check (user_id <> blocked_id)
);

-- ---------------------------------------------------------------------------
-- Helpers (security definer so policies can use them without recursion)
-- ---------------------------------------------------------------------------

create or replace function public.is_member(p_gym uuid) returns boolean
language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.gym_members m where m.gym_id = p_gym and m.user_id = auth.uid()
  );
$$;

create or replace function public.can_view_gym(p_gym uuid) returns boolean
language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.gyms g
    where g.id = p_gym and (g.kind = 'public' or public.is_member(g.id))
  );
$$;

-- ---------------------------------------------------------------------------
-- Triggers
-- ---------------------------------------------------------------------------

-- Profile row for every new account, using the username chosen at sign-up.
create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  insert into public.profiles (id, username, companion_id)
  values (
    new.id,
    lower(new.raw_user_meta_data ->> 'username'),
    coalesce(new.raw_user_meta_data ->> 'companion_id', 'kong')
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Private gyms get an invite code; creators always join their own gym.
create or replace function public.before_gym_insert() returns trigger
language plpgsql set search_path = '' as $$
begin
  new.created_by := auth.uid();
  new.name := btrim(new.name);
  new.area := nullif(btrim(coalesce(new.area, '')), '');
  if new.kind = 'private' then
    new.invite_code := upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 6));
  else
    new.invite_code := null;
  end if;
  return new;
end;
$$;

drop trigger if exists gyms_before_insert on public.gyms;
create trigger gyms_before_insert
  before insert on public.gyms
  for each row execute function public.before_gym_insert();

create or replace function public.after_gym_insert() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  if new.created_by is not null then
    insert into public.gym_members (gym_id, user_id) values (new.id, new.created_by)
    on conflict do nothing;
  end if;
  return new;
end;
$$;

drop trigger if exists gyms_after_insert on public.gyms;
create trigger gyms_after_insert
  after insert on public.gyms
  for each row execute function public.after_gym_insert();

-- New entries: server decides status, and posting is rate limited.
create or replace function public.before_entry_insert() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  if (select count(*) from public.entries e
      where e.user_id = new.user_id and e.created_at > now() - interval '1 day') >= 30 then
    raise exception 'Too many attempts today. Try again tomorrow.' using errcode = 'P0001';
  end if;
  -- Becomes 'processing' once the video moderation scan is connected (docs/gyms-spec.md).
  new.status := 'live';
  new.created_at := now();
  return new;
end;
$$;

drop trigger if exists entries_before_insert on public.entries;
create trigger entries_before_insert
  before insert on public.entries
  for each row execute function public.before_entry_insert();

-- Reports: decide whether the report counts, then hide the entry at the threshold.
create or replace function public.before_report_insert() returns trigger
language plpgsql security definer set search_path = '' as $$
declare
  reporter public.profiles;
begin
  select * into reporter from public.profiles where id = new.reporter_id;
  new.counted := reporter.created_at <= now() - interval '7 days' and reporter.strikes < 3;
  new.resolved := false;
  return new;
end;
$$;

drop trigger if exists reports_before_insert on public.reports;
create trigger reports_before_insert
  before insert on public.reports
  for each row execute function public.before_report_insert();

create or replace function public.after_report_insert() returns trigger
language plpgsql security definer set search_path = '' as $$
declare
  invalid_count int;
  inappropriate_count int;
begin
  select
    count(*) filter (where kind = 'invalid' and counted),
    count(*) filter (where kind = 'inappropriate' and counted)
  into invalid_count, inappropriate_count
  from public.reports where entry_id = new.entry_id;

  if invalid_count >= 3 or inappropriate_count >= 1 then
    update public.entries set status = 'hidden' where id = new.entry_id and status = 'live';
  end if;
  return new;
end;
$$;

drop trigger if exists reports_after_insert on public.reports;
create trigger reports_after_insert
  after insert on public.reports
  for each row execute function public.after_report_insert();

-- ---------------------------------------------------------------------------
-- RPCs
-- ---------------------------------------------------------------------------

-- Private gyms are invisible to non-members, so joining by code needs a definer function.
create or replace function public.join_gym_by_invite(p_code text) returns uuid
language plpgsql security definer set search_path = '' as $$
declare
  gym_id uuid;
begin
  if auth.uid() is null then
    raise exception 'Sign in first' using errcode = '42501';
  end if;
  select id into gym_id from public.gyms where invite_code = upper(btrim(p_code));
  if gym_id is not null then
    insert into public.gym_members (gym_id, user_id) values (gym_id, auth.uid())
    on conflict do nothing;
  end if;
  return gym_id;
end;
$$;

-- Lets the sign-up form check a username before creating the account.
create or replace function public.username_available(p_username text) returns boolean
language sql stable security definer set search_path = '' as $$
  select not exists (select 1 from public.profiles where username = lower(p_username));
$$;

revoke execute on function public.join_gym_by_invite(text) from public, anon;
grant execute on function public.join_gym_by_invite(text) to authenticated;
grant execute on function public.username_available(text) to anon, authenticated;
revoke execute on function public.is_member(uuid), public.can_view_gym(uuid) from public, anon;
grant execute on function public.is_member(uuid), public.can_view_gym(uuid) to authenticated;

-- ---------------------------------------------------------------------------
-- Row level security
-- ---------------------------------------------------------------------------

alter table public.profiles enable row level security;
alter table public.gyms enable row level security;
alter table public.gym_members enable row level security;
alter table public.entries enable row level security;
alter table public.reports enable row level security;
alter table public.blocks enable row level security;

-- Profiles: usernames are public to signed-in users; you can edit your handle and buddy.
drop policy if exists "profiles readable" on public.profiles;
create policy "profiles readable" on public.profiles
  for select to authenticated using (true);
drop policy if exists "profiles self update" on public.profiles;
create policy "profiles self update" on public.profiles
  for update to authenticated using (id = auth.uid()) with check (id = auth.uid());
revoke update on public.profiles from authenticated;
grant update (username, companion_id) on public.profiles to authenticated;

-- Gyms: public ones are visible to everyone signed in, private ones to members.
-- created_by covers insert-then-read, which runs before the creator's membership row exists.
drop policy if exists "gyms visible" on public.gyms;
create policy "gyms visible" on public.gyms
  for select to authenticated using (kind = 'public' or created_by = auth.uid() or public.is_member(id));
drop policy if exists "gyms create" on public.gyms;
create policy "gyms create" on public.gyms
  for insert to authenticated with check (auth.uid() is not null);

-- Memberships: visible for gyms you can see (member counts); join public gyms, leave any.
drop policy if exists "members visible" on public.gym_members;
create policy "members visible" on public.gym_members
  for select to authenticated using (user_id = auth.uid() or public.can_view_gym(gym_id));
drop policy if exists "members join public" on public.gym_members;
create policy "members join public" on public.gym_members
  for insert to authenticated with check (
    user_id = auth.uid()
    and exists (select 1 from public.gyms g where g.id = gym_id and g.kind = 'public')
  );
drop policy if exists "members leave" on public.gym_members;
create policy "members leave" on public.gym_members
  for delete to authenticated using (user_id = auth.uid());

-- Entries: live entries in gyms you can see, minus blocked users and content you reported
-- as inappropriate. You always see your own. Post only to gyms you belong to.
drop policy if exists "entries visible" on public.entries;
create policy "entries visible" on public.entries
  for select to authenticated using (
    user_id = auth.uid()
    or (
      status = 'live'
      and public.can_view_gym(gym_id)
      and not exists (
        select 1 from public.blocks b where b.user_id = auth.uid() and b.blocked_id = entries.user_id
      )
      and not exists (
        select 1 from public.reports r
        where r.entry_id = entries.id and r.reporter_id = auth.uid() and r.kind = 'inappropriate'
      )
    )
  );
drop policy if exists "entries post" on public.entries;
create policy "entries post" on public.entries
  for insert to authenticated with check (
    user_id = auth.uid()
    and public.is_member(gym_id)
    and video_path like auth.uid()::text || '/%'
  );
drop policy if exists "entries delete own" on public.entries;
create policy "entries delete own" on public.entries
  for delete to authenticated using (user_id = auth.uid());

-- Reports: file on entries you can see (not your own); read your own reports.
drop policy if exists "reports file" on public.reports;
create policy "reports file" on public.reports
  for insert to authenticated with check (
    reporter_id = auth.uid()
    and exists (
      select 1 from public.entries e
      where e.id = entry_id and e.user_id <> auth.uid() and public.can_view_gym(e.gym_id)
    )
  );
drop policy if exists "reports own" on public.reports;
create policy "reports own" on public.reports
  for select to authenticated using (reporter_id = auth.uid());

-- Blocks: yours only.
drop policy if exists "blocks own" on public.blocks;
create policy "blocks own" on public.blocks
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

-- ---------------------------------------------------------------------------
-- Video storage: private bucket, one folder per user, readable when the entry is.
-- ---------------------------------------------------------------------------

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('attempts', 'attempts', false, 104857600, array['video/mp4', 'video/quicktime', 'video/webm'])
on conflict (id) do nothing;

drop policy if exists "attempts upload own folder" on storage.objects;
create policy "attempts upload own folder" on storage.objects
  for insert to authenticated with check (
    bucket_id = 'attempts' and (storage.foldername(name))[1] = auth.uid()::text
  );
drop policy if exists "attempts read" on storage.objects;
create policy "attempts read" on storage.objects
  for select to authenticated using (
    bucket_id = 'attempts'
    and (
      (storage.foldername(name))[1] = auth.uid()::text
      or exists (
        select 1 from public.entries e
        where e.video_path = storage.objects.name
          and e.status = 'live'
          and public.can_view_gym(e.gym_id)
      )
    )
  );
drop policy if exists "attempts delete own" on storage.objects;
create policy "attempts delete own" on storage.objects
  for delete to authenticated using (
    bucket_id = 'attempts' and (storage.foldername(name))[1] = auth.uid()::text
  );

-- ===== 20261001000000_moderation_accounts.sql =====
-- Gymmy: admin review, strikes and bans, Sign in with Apple usernames, account deletion.
-- Run once in the Supabase SQL Editor after 20260930000000_gyms.sql.

-- ---------------------------------------------------------------------------
-- Profile flags
-- ---------------------------------------------------------------------------

alter table public.profiles
  add column if not exists is_admin boolean not null default false,
  -- False for generated handles (Sign in with Apple has no username); the app asks the user to pick one.
  add column if not exists username_set boolean not null default true,
  -- Rejected reports: three and your reports stop counting.
  add column if not exists report_rejections int not null default 0,
  -- Set after three strikes for removed entries; banned accounts can't post or report.
  add column if not exists banned_at timestamptz;

create or replace function public.is_admin() returns boolean
language sql stable security definer set search_path = '' as $$
  select coalesce((select p.is_admin from public.profiles p where p.id = auth.uid()), false);
$$;
revoke execute on function public.is_admin() from public, anon;
grant execute on function public.is_admin() to authenticated;

-- Accounts without a chosen username (e.g. Sign in with Apple) get a placeholder.
create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path = '' as $$
declare
  chosen text := lower(new.raw_user_meta_data ->> 'username');
begin
  if chosen is null or chosen !~ '^[a-z0-9_.]{3,20}$'
     or exists (select 1 from public.profiles where username = chosen) then
    insert into public.profiles (id, username, companion_id, username_set)
    values (
      new.id,
      'lifter_' || substr(md5(new.id::text), 1, 8),
      coalesce(new.raw_user_meta_data ->> 'companion_id', 'kong'),
      false
    );
  else
    insert into public.profiles (id, username, companion_id)
    values (new.id, chosen, coalesce(new.raw_user_meta_data ->> 'companion_id', 'kong'));
  end if;
  return new;
end;
$$;

-- Picking a new username marks it as chosen.
create or replace function public.before_profile_update() returns trigger
language plpgsql set search_path = '' as $$
begin
  new.username := lower(new.username);
  if new.username is distinct from old.username then
    new.username_set := true;
  end if;
  return new;
end;
$$;

drop trigger if exists profiles_before_update on public.profiles;
create trigger profiles_before_update
  before update on public.profiles
  for each row execute function public.before_profile_update();

-- ---------------------------------------------------------------------------
-- Enforcement: banned accounts can't post; rejected reporters stop counting.
-- ---------------------------------------------------------------------------

create or replace function public.before_entry_insert() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  if exists (select 1 from public.profiles where id = new.user_id and banned_at is not null) then
    raise exception 'This account can no longer post.' using errcode = 'P0001';
  end if;
  if (select count(*) from public.entries e
      where e.user_id = new.user_id and e.created_at > now() - interval '1 day') >= 30 then
    raise exception 'Too many attempts today. Try again tomorrow.' using errcode = 'P0001';
  end if;
  -- Becomes 'processing' once the video moderation scan is connected (docs/gyms-spec.md).
  new.status := 'live';
  new.created_at := now();
  return new;
end;
$$;

create or replace function public.before_report_insert() returns trigger
language plpgsql security definer set search_path = '' as $$
declare
  reporter public.profiles;
begin
  select * into reporter from public.profiles where id = new.reporter_id;
  new.counted := reporter.created_at <= now() - interval '7 days'
    and reporter.report_rejections < 3
    and reporter.banned_at is null;
  new.resolved := false;
  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- Admin review
-- ---------------------------------------------------------------------------

-- Hidden entries waiting for a decision, inappropriate-content reports first.
drop function if exists public.admin_review_queue();
create or replace function public.admin_review_queue()
returns table (
  entry_id uuid,
  gym_name text,
  challenge_id text,
  username text,
  value numeric,
  bodyweight_kg numeric,
  video_path text,
  created_at timestamptz,
  inappropriate_reports int,
  invalid_reports int,
  reasons text[]
)
language plpgsql stable security definer set search_path = '' as $$
begin
  if not public.is_admin() then
    raise exception 'Admins only' using errcode = '42501';
  end if;
  return query
    select e.id, g.name, e.challenge_id, p.username, e.value, e.bodyweight_kg, e.video_path, e.created_at,
      count(*) filter (where r.kind = 'inappropriate')::int,
      count(*) filter (where r.kind = 'invalid')::int,
      array_agg(distinct r.reason)
    from public.entries e
    join public.gyms g on g.id = e.gym_id
    join public.profiles p on p.id = e.user_id
    join public.reports r on r.entry_id = e.id and not r.resolved
    where e.status = 'hidden'
    group by e.id, g.name, p.username
    order by count(*) filter (where r.kind = 'inappropriate') desc, e.created_at;
end;
$$;

-- 'restore' puts the entry back and counts a rejection against each reporter.
-- 'remove' takes it down for good and gives the poster a strike (three strikes bans).
create or replace function public.admin_resolve(p_entry uuid, p_decision text) returns void
language plpgsql security definer set search_path = '' as $$
declare
  owner uuid;
begin
  if not public.is_admin() then
    raise exception 'Admins only' using errcode = '42501';
  end if;
  if p_decision not in ('restore', 'remove') then
    raise exception 'Unknown decision %', p_decision;
  end if;

  select user_id into owner from public.entries where id = p_entry;
  if owner is null then
    raise exception 'Entry not found';
  end if;

  if p_decision = 'restore' then
    update public.entries set status = 'live' where id = p_entry;
    update public.profiles set report_rejections = report_rejections + 1
      where id in (select reporter_id from public.reports where entry_id = p_entry and not resolved);
  else
    update public.entries set status = 'removed' where id = p_entry;
    update public.profiles
      set strikes = strikes + 1,
          banned_at = case when strikes + 1 >= 3 then coalesce(banned_at, now()) else banned_at end
      where id = owner;
  end if;
  update public.reports set resolved = true where entry_id = p_entry;
end;
$$;

revoke execute on function public.admin_review_queue(), public.admin_resolve(uuid, text) from public, anon;
grant execute on function public.admin_review_queue(), public.admin_resolve(uuid, text) to authenticated;

-- Admins can watch videos of hidden entries to review them.
drop policy if exists "attempts read" on storage.objects;
create policy "attempts read" on storage.objects
  for select to authenticated using (
    bucket_id = 'attempts'
    and (
      (storage.foldername(name))[1] = auth.uid()::text
      or public.is_admin()
      or exists (
        select 1 from public.entries e
        where e.video_path = storage.objects.name
          and e.status = 'live'
          and public.can_view_gym(e.gym_id)
      )
    )
  );

-- Banned accounts can't file reports.
drop policy if exists "reports file" on public.reports;
create policy "reports file" on public.reports
  for insert to authenticated with check (
    reporter_id = auth.uid()
    and not exists (select 1 from public.profiles p where p.id = auth.uid() and p.banned_at is not null)
    and exists (
      select 1 from public.entries e
      where e.id = entry_id and e.user_id <> auth.uid() and public.can_view_gym(e.gym_id)
    )
  );

-- ---------------------------------------------------------------------------
-- Account deletion (App Store requirement). Entries, reports, memberships and
-- blocks cascade from the profile; the app deletes the user's videos first.
-- ---------------------------------------------------------------------------

create or replace function public.delete_my_account() returns void
language plpgsql security definer set search_path = '' as $$
begin
  if auth.uid() is null then
    raise exception 'Sign in first' using errcode = '42501';
  end if;
  delete from auth.users where id = auth.uid();
end;
$$;

revoke execute on function public.delete_my_account() from public, anon;
grant execute on function public.delete_my_account() to authenticated;

-- ===== 20261002000000_video_scan.sql =====
-- Gymmy: automatic video scan (Hive) before entries go live.
-- Run once in the Supabase SQL Editor after the earlier migrations.
-- The scan stays off until you deploy the `moderate-entry` Edge Function, add the
-- HIVE_API_KEY secret, then run:
--   update public.app_settings set value = 'true' where key = 'moderation_enabled';

create table if not exists public.app_settings (
  key text primary key,
  value jsonb not null
);
alter table public.app_settings enable row level security; -- no policies: server-side only

insert into public.app_settings (key, value) values ('moderation_enabled', 'false')
on conflict (key) do nothing;

create table if not exists public.moderation_results (
  entry_id uuid primary key references public.entries (id) on delete cascade,
  provider text not null,
  flagged boolean not null default false,
  flag_class text,
  flag_score numeric,
  -- Set when the scan couldn't run; the entry then waits for a person.
  error text,
  created_at timestamptz not null default now()
);
alter table public.moderation_results enable row level security; -- written by the Edge Function only

-- New entries wait in 'processing' for the scan when it's switched on.
create or replace function public.before_entry_insert() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  if exists (select 1 from public.profiles where id = new.user_id and banned_at is not null) then
    raise exception 'This account can no longer post.' using errcode = 'P0001';
  end if;
  if (select count(*) from public.entries e
      where e.user_id = new.user_id and e.created_at > now() - interval '1 day') >= 30 then
    raise exception 'Too many attempts today. Try again tomorrow.' using errcode = 'P0001';
  end if;
  new.status := case
    when coalesce((select value = 'true'::jsonb from public.app_settings where key = 'moderation_enabled'), false)
      then 'processing'
    else 'live'
  end;
  new.created_at := now();
  return new;
end;
$$;

-- The review queue now also holds entries the scan flagged or couldn't check,
-- and entries stuck waiting for a scan for more than 15 minutes.
drop function if exists public.admin_review_queue();
create or replace function public.admin_review_queue()
returns table (
  entry_id uuid,
  gym_name text,
  challenge_id text,
  username text,
  value numeric,
  bodyweight_kg numeric,
  video_path text,
  created_at timestamptz,
  inappropriate_reports int,
  invalid_reports int,
  reasons text[],
  scan_flag text,
  scan_score numeric,
  scan_error text,
  status text
)
language plpgsql stable security definer set search_path = '' as $$
begin
  if not public.is_admin() then
    raise exception 'Admins only' using errcode = '42501';
  end if;
  return query
    select e.id, g.name, e.challenge_id, p.username, e.value, e.bodyweight_kg, e.video_path, e.created_at,
      (count(r.*) filter (where r.kind = 'inappropriate'))::int,
      (count(r.*) filter (where r.kind = 'invalid'))::int,
      coalesce(array_remove(array_agg(distinct r.reason), null), '{}'),
      m.flag_class, m.flag_score, m.error, e.status
    from public.entries e
    join public.gyms g on g.id = e.gym_id
    join public.profiles p on p.id = e.user_id
    left join public.reports r on r.entry_id = e.id and not r.resolved
    left join public.moderation_results m on m.entry_id = e.id
    where (e.status = 'hidden' and (r.entry_id is not null or m.flagged or m.error is not null))
       or (e.status = 'processing' and e.created_at < now() - interval '15 minutes')
    group by e.id, g.name, p.username, m.flag_class, m.flag_score, m.error, m.flagged
    order by (m.flagged is true) desc,
      count(r.*) filter (where r.kind = 'inappropriate') desc,
      e.created_at;
end;
$$;

revoke execute on function public.admin_review_queue() from public, anon;
grant execute on function public.admin_review_queue() to authenticated;

-- Resolving also clears entries still waiting for a scan.
create or replace function public.admin_resolve(p_entry uuid, p_decision text) returns void
language plpgsql security definer set search_path = '' as $$
declare
  owner uuid;
begin
  if not public.is_admin() then
    raise exception 'Admins only' using errcode = '42501';
  end if;
  if p_decision not in ('restore', 'remove') then
    raise exception 'Unknown decision %', p_decision;
  end if;

  select user_id into owner from public.entries where id = p_entry;
  if owner is null then
    raise exception 'Entry not found';
  end if;

  if p_decision = 'restore' then
    update public.entries set status = 'live' where id = p_entry;
    update public.profiles set report_rejections = report_rejections + 1
      where id in (select reporter_id from public.reports where entry_id = p_entry and not resolved);
  else
    update public.entries set status = 'removed' where id = p_entry;
    update public.profiles
      set strikes = strikes + 1,
          banned_at = case when strikes + 1 >= 3 then coalesce(banned_at, now()) else banned_at end
      where id = owner;
  end if;
  update public.reports set resolved = true where entry_id = p_entry;
end;
$$;

-- ===== 20261003000000_map_places.sql =====
-- Gymmy: gyms linked to real places from OpenStreetMap.
-- Safe to re-run. Included in supabase/setup.sql.

alter table public.gyms
  add column if not exists place_id text,
  add column if not exists lat double precision,
  add column if not exists lng double precision;

-- One Gymmy gym per map place.
create unique index if not exists gyms_place_id on public.gyms (place_id) where place_id is not null;

-- Name+area uniqueness only applies to hand-added gyms; map places can share a name
-- (two branches of the same chain in one city).
drop index if exists public.gyms_public_name_area;
create unique index if not exists gyms_public_name_area_manual
  on public.gyms (lower(btrim(name)), lower(coalesce(btrim(area), '')))
  where kind = 'public' and place_id is null;

-- Only join_place_gym (running as the table owner) may link a gym to a map place;
-- direct inserts from the app can't claim a place under a made-up name.
create or replace function public.before_gym_insert() returns trigger
language plpgsql set search_path = '' as $$
begin
  new.created_by := auth.uid();
  new.name := btrim(new.name);
  new.area := nullif(btrim(coalesce(new.area, '')), '');
  if current_user in ('authenticated', 'anon') then
    new.place_id := null;
    new.lat := null;
    new.lng := null;
  end if;
  if new.kind = 'private' then
    new.invite_code := upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 6));
    new.place_id := null;
  else
    new.invite_code := null;
  end if;
  return new;
end;
$$;

-- Joins the Gymmy gym for a map place, creating it on first use. Returns the gym id.
create or replace function public.join_place_gym(
  p_place_id text,
  p_name text,
  p_area text,
  p_lat double precision,
  p_lng double precision
) returns uuid
language plpgsql security definer set search_path = '' as $$
declare
  gym_id uuid;
begin
  if auth.uid() is null then
    raise exception 'Sign in first' using errcode = '42501';
  end if;
  if p_place_id !~ '^osm:(node|way|relation)/[0-9]+$' then
    raise exception 'Invalid place id' using errcode = '22023';
  end if;

  select id into gym_id from public.gyms where place_id = p_place_id;
  if gym_id is null then
    insert into public.gyms (kind, name, area, place_id, lat, lng)
    values ('public', left(btrim(p_name), 40), left(nullif(btrim(p_area), ''), 40), p_place_id, p_lat, p_lng)
    on conflict (place_id) where place_id is not null do nothing
    returning id into gym_id;
    if gym_id is null then
      select id into gym_id from public.gyms where place_id = p_place_id;
    end if;
  end if;

  insert into public.gym_members (gym_id, user_id) values (gym_id, auth.uid())
  on conflict do nothing;
  return gym_id;
end;
$$;

revoke execute on function public.join_place_gym(text, text, text, double precision, double precision) from public, anon;
grant execute on function public.join_place_gym(text, text, text, double precision, double precision) to authenticated;

-- ===== 20261004000000_exercise_submissions.sql =====
-- Gymmy: custom exercises submitted for review. Approved ones are added to everyone's exercise list.
-- Safe to re-run.

create table if not exists public.exercise_submissions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references public.profiles (id) on delete cascade,
  name text not null check (char_length(name) between 2 and 40),
  muscle_group text not null check (muscle_group in ('chest', 'back', 'legs', 'shoulders', 'arms', 'core', 'cardio')),
  kind text not null check (kind in ('weight', 'reps', 'duration')),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

create index if not exists exercise_submissions_user on public.exercise_submissions (user_id);
-- One approved exercise per name.
create unique index if not exists exercise_submissions_approved_name
  on public.exercise_submissions (lower(name)) where status = 'approved';

-- Submissions always start pending; banned accounts can't submit; ten a day at most.
create or replace function public.before_exercise_submission_insert() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  if exists (select 1 from public.profiles where id = new.user_id and banned_at is not null) then
    raise exception 'This account can no longer submit exercises.' using errcode = 'P0001';
  end if;
  if (select count(*) from public.exercise_submissions s
      where s.user_id = new.user_id and s.created_at > now() - interval '1 day') >= 10 then
    raise exception 'Too many submissions today. Try again tomorrow.' using errcode = 'P0001';
  end if;
  new.name := btrim(regexp_replace(new.name, '\s+', ' ', 'g'));
  new.status := 'pending';
  new.created_at := now();
  new.reviewed_at := null;
  return new;
end;
$$;

drop trigger if exists exercise_submissions_before_insert on public.exercise_submissions;
create trigger exercise_submissions_before_insert
  before insert on public.exercise_submissions
  for each row execute function public.before_exercise_submission_insert();

alter table public.exercise_submissions enable row level security;

-- Approved exercises are public; you can see your own submissions; admins see everything.
drop policy if exists "exercise submissions visible" on public.exercise_submissions;
create policy "exercise submissions visible" on public.exercise_submissions
  for select to authenticated using (
    status = 'approved' or user_id = auth.uid() or public.is_admin()
  );
drop policy if exists "approved exercises public" on public.exercise_submissions;
create policy "approved exercises public" on public.exercise_submissions
  for select to anon using (status = 'approved');

drop policy if exists "exercise submissions create" on public.exercise_submissions;
create policy "exercise submissions create" on public.exercise_submissions
  for insert to authenticated with check (user_id = auth.uid());

-- Pending submissions, oldest first.
drop function if exists public.admin_exercise_submissions();
create or replace function public.admin_exercise_submissions()
returns table (id uuid, name text, muscle_group text, kind text, username text, created_at timestamptz)
language plpgsql stable security definer set search_path = '' as $$
begin
  if not public.is_admin() then
    raise exception 'Admins only' using errcode = '42501';
  end if;
  return query
    select s.id, s.name, s.muscle_group, s.kind, p.username, s.created_at
    from public.exercise_submissions s
    join public.profiles p on p.id = s.user_id
    where s.status = 'pending'
    order by s.created_at;
end;
$$;

-- Approve (optionally fixing the name) or reject a submission.
create or replace function public.admin_resolve_exercise(p_id uuid, p_decision text, p_name text default null)
returns void
language plpgsql security definer set search_path = '' as $$
begin
  if not public.is_admin() then
    raise exception 'Admins only' using errcode = '42501';
  end if;
  if p_decision not in ('approve', 'reject') then
    raise exception 'Unknown decision %', p_decision;
  end if;
  update public.exercise_submissions
    set status = case when p_decision = 'approve' then 'approved' else 'rejected' end,
        name = case when p_decision = 'approve' and nullif(btrim(p_name), '') is not null
                    then btrim(regexp_replace(p_name, '\s+', ' ', 'g')) else name end,
        reviewed_at = now()
    where id = p_id and status = 'pending';
  if not found then
    raise exception 'Submission not found or already reviewed';
  end if;
exception when unique_violation then
  raise exception 'An approved exercise already has that name.' using errcode = 'P0001';
end;
$$;

revoke execute on function public.admin_exercise_submissions(), public.admin_resolve_exercise(uuid, text, text)
  from public, anon;
grant execute on function public.admin_exercise_submissions(), public.admin_resolve_exercise(uuid, text, text)
  to authenticated;

-- ===== 20261005000000_distance_kind.sql =====
-- Gymmy: custom exercises can be tracked by distance + time. Safe to re-run.
alter table public.exercise_submissions drop constraint if exists exercise_submissions_kind_check;
alter table public.exercise_submissions
  add constraint exercise_submissions_kind_check check (kind in ('weight', 'reps', 'duration', 'distance'));

-- ===== 20261006000000_sync.sql =====
-- Gymmy: cloud backup and sync of each user's training data. Safe to re-run.
--
-- One row per synced record (a workout, a check-in, a companion, ...), stored as JSON.
-- Clients push changes with the time they were made and pull everything changed since
-- their last pull. The newest edit of a record wins.

create table if not exists public.sync_records (
  user_id uuid not null default auth.uid() references public.profiles (id) on delete cascade,
  kind text not null check (kind in ('meta', 'workout', 'check_in', 'custom_exercise', 'companion', 'milestone')),
  id text not null check (char_length(id) between 1 and 100),
  data jsonb,
  deleted boolean not null default false,
  -- When the change was made on the device (decides which edit wins).
  updated_at timestamptz not null,
  -- When the server stored it (the pull cursor).
  server_updated_at timestamptz not null default clock_timestamp(),
  primary key (user_id, kind, id),
  constraint sync_records_size check (octet_length(coalesce(data::text, '')) <= 65536)
);

create index if not exists sync_records_pull on public.sync_records (user_id, server_updated_at);

create or replace function public.before_sync_record_write() returns trigger
language plpgsql set search_path = '' as $$
begin
  new.server_updated_at := clock_timestamp();
  -- Clocks drift; don't let a device claim a time far in the future.
  if new.updated_at > now() + interval '1 day' then
    new.updated_at := now();
  end if;
  if new.deleted then
    new.data := null;
  end if;
  return new;
end;
$$;

drop trigger if exists sync_records_before_write on public.sync_records;
create trigger sync_records_before_write
  before insert or update on public.sync_records
  for each row execute function public.before_sync_record_write();

alter table public.sync_records enable row level security;

drop policy if exists "sync records own" on public.sync_records;
create policy "sync records own" on public.sync_records
  for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

revoke all on public.sync_records from anon;

-- Saves a batch of changes. A record is only overwritten by a newer edit.
-- Returns how many records changed.
create or replace function public.sync_push(p_records jsonb) returns int
language plpgsql security invoker set search_path = '' as $$
declare
  changed int;
begin
  if auth.uid() is null then
    raise exception 'Sign in first' using errcode = '42501';
  end if;
  if jsonb_typeof(p_records) <> 'array' or jsonb_array_length(p_records) > 500 then
    raise exception 'Send up to 500 records at a time' using errcode = '22023';
  end if;
  insert into public.sync_records as s (user_id, kind, id, data, deleted, updated_at)
    select auth.uid(), r.kind, r.id, r.data, coalesce(r.deleted, false), r.updated_at
    from jsonb_to_recordset(p_records) as r(kind text, id text, data jsonb, deleted boolean, updated_at timestamptz)
  on conflict (user_id, kind, id) do update
    set data = excluded.data, deleted = excluded.deleted, updated_at = excluded.updated_at
    where s.updated_at <= excluded.updated_at;
  get diagnostics changed = row_count;
  return changed;
end;
$$;

revoke execute on function public.sync_push(jsonb) from public, anon;
grant execute on function public.sync_push(jsonb) to authenticated;

-- ===== 20261007000000_analytics.sql =====
-- Gymmy: privacy-safe, first-party product analytics. Safe to re-run.
--
-- Events carry a random per-install id (never the account id), a name from a fixed set of
-- shapes, and a few small typed properties chosen by the app (no free text, no health or
-- workout values, numbers bucketed). Clients can only add events through track_events;
-- nobody can read them through the API. Events older than 180 days are removed.

create table if not exists public.analytics_events (
  id bigint generated always as identity primary key,
  install_id uuid not null,
  event text not null check (event ~ '^[a-z][a-z_]{1,39}$'),
  props jsonb not null default '{}' check (jsonb_typeof(props) = 'object' and octet_length(props::text) <= 1024),
  app_version text check (char_length(app_version) <= 40),
  platform text check (platform in ('ios', 'android', 'web')),
  client_at timestamptz not null,
  received_at timestamptz not null default now()
);

create index if not exists analytics_events_received on public.analytics_events (received_at);
create index if not exists analytics_events_event on public.analytics_events (event, received_at);
create index if not exists analytics_events_install on public.analytics_events (install_id, received_at);

alter table public.analytics_events enable row level security;
-- No policies: the API can't read or write the table directly; track_events is the only way in.
revoke all on public.analytics_events from anon, authenticated;

-- Adds up to 50 events. Each install can send up to 1,000 events a day; extra ones are dropped.
create or replace function public.track_events(p_install uuid, p_events jsonb) returns int
language plpgsql security definer set search_path = '' as $$
declare
  today int;
  room int;
  added int;
begin
  if p_install is null or jsonb_typeof(p_events) <> 'array' or jsonb_array_length(p_events) > 50 then
    raise exception 'Send up to 50 events at a time' using errcode = '22023';
  end if;

  select count(*) into today from public.analytics_events
    where install_id = p_install and received_at > now() - interval '1 day';
  room := greatest(0, 1000 - today);
  if room = 0 then
    return 0;
  end if;

  insert into public.analytics_events (install_id, event, props, app_version, platform, client_at)
    select p_install, e.event, coalesce(e.props, '{}'), e.app_version, e.platform,
           -- Clocks drift; keep client times within a sane window.
           least(greatest(coalesce(e.client_at, now()), now() - interval '7 days'), now())
    from jsonb_to_recordset(p_events)
      as e(event text, props jsonb, app_version text, platform text, client_at timestamptz)
    where e.event ~ '^[a-z][a-z_]{1,39}$'
    limit room;
  get diagnostics added = row_count;

  -- Retention: now and then, clear out events older than 180 days.
  if random() < 0.01 then
    delete from public.analytics_events
      where id in (select id from public.analytics_events
                   where received_at < now() - interval '180 days' limit 5000);
  end if;
  return added;
end;
$$;

revoke execute on function public.track_events(uuid, jsonb) from public;
grant execute on function public.track_events(uuid, jsonb) to anon, authenticated;

-- ===== 20261008000000_more_challenges.sql =====
-- More challenges: 2 km row, mile run, 5K run and farmers carry. Safe to re-run.
alter table public.entries drop constraint if exists entries_challenge_id_check;
alter table public.entries add constraint entries_challenge_id_check check (challenge_id in (
  'bench_1rm', 'squat_1rm', 'deadlift_1rm', 'ohp_1rm',
  'pullups_max', 'pushups_1min', 'plank_hold', 'row_500m',
  'row_2k', 'run_1mi', 'run_5k', 'farmers_carry'));

-- ===== 20261009000000_sync_custom_plans.sql =====
-- Custom training plans sync like custom exercises. Safe to re-run.
alter table public.sync_records drop constraint if exists sync_records_kind_check;
alter table public.sync_records add constraint sync_records_kind_check check (kind in (
  'meta', 'workout', 'check_in', 'custom_exercise', 'custom_program', 'companion', 'milestone'));
