#!/usr/bin/env bash
# Concatenates every migration into supabase/setup.sql: one idempotent script to paste into the
# Supabase SQL Editor. Safe to run more than once; it fills in whatever is missing.
set -euo pipefail
cd "$(dirname "$0")/.."
{
  echo "-- Gymmy database setup. Generated by scripts/build-setup-sql.sh from supabase/migrations."
  echo "-- Paste the whole file into Supabase → SQL Editor → New query → Run. Safe to re-run."
  for f in supabase/migrations/*.sql; do
    echo
    echo "-- ===== $(basename "$f") ====="
    cat "$f"
  done
} > supabase/setup.sql
echo "Wrote supabase/setup.sql"
